# Generated by Django 3.0.6 on 2020-05-21 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CellLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'newly imported'), ('ok', 'validated')], default='new', max_length=255, null=True)),
                ('comments', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('aliases', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'cell lines',
            },
        ),
        migrations.CreateModel(
            name='CellPops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'newly imported'), ('ok', 'validated')], default='new', max_length=255, null=True)),
                ('comments', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('aliases', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'cell populations',
            },
        ),
        migrations.CreateModel(
            name='CellTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'newly imported'), ('ok', 'validated')], default='new', max_length=255, null=True)),
                ('comments', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('aliases', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'cell types',
            },
        ),
        migrations.CreateModel(
            name='DiseaseStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('comments', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'newly imported'), ('ok', 'validated')], default='new', max_length=255, null=True)),
                ('aliases', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'disease states',
            },
        ),
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('issn', models.CharField(blank=True, default='', max_length=9, null=True)),
                ('impact_factor', models.FloatField(default=0.0, null=True)),
            ],
            options={
                'verbose_name_plural': 'journals',
            },
        ),
        migrations.CreateModel(
            name='TissueTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'newly imported'), ('ok', 'validated')], default='new', max_length=255, null=True)),
                ('comments', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('aliases', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'tissues',
            },
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.IntegerField(blank=True, default=None, null=True)),
                ('unique_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('reference', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('abstract', models.TextField(blank=True, default='', null=True)),
                ('pub_date', models.DateField(blank=True, default=None, null=True)),
                ('date_collected', models.DateTimeField(blank=True, default=None, null=True)),
                ('authors', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('last_auth_email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('status', models.CharField(blank=True, choices=[('imported', 'paper entered awaiting datasets'), ('datasets', 'datasets imported awaiting download'), ('transfer', 'datasets download in progress'), ('downloaded', 'datasets downloaded awaiting analysis'), ('complete', 'analysis complete/complete'), ('error', 'error/hold- see comments')], default='imported', max_length=255, null=True)),
                ('comments', models.TextField(blank=True, default='', null=True)),
                ('lab', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('pub_summary', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('journal', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacollection.Journals')),
            ],
            options={
                'verbose_name_plural': 'papers',
            },
        ),
    ]
