# Generated by Django 3.0.4 on 2020-04-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollect',
            fields=[
                ('dataset_name', models.CharField(db_column='Dataset Name', max_length=100, primary_key=True, serialize=False)),
                ('dataset_id', models.CharField(db_column='Dataset ID', max_length=50)),
                ('cancer', models.CharField(db_column='Cancer Type', max_length=50)),
                ('platform', models.CharField(db_column='Platform', max_length=50)),
                ('patient', models.IntegerField(db_column='Patient Number')),
                ('cell', models.IntegerField(db_column='Cell Number')),
                ('publication', models.CharField(db_column='Publication', max_length=100)),
                ('pmid', models.CharField(db_column='PMID', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExpLISA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(db_column='Dataset ID', max_length=50)),
                ('cancer', models.CharField(db_column='Cancer Type', max_length=50)),
                ('subcluster', models.CharField(db_column='Subcluster', max_length=50)),
                ('tf', models.CharField(db_column='Transcription Factor', max_length=20)),
                ('expression', models.DecimalField(db_column='Expression', decimal_places=2, max_digits=5)),
                ('regscore', models.DecimalField(db_column='Regulatory Score', decimal_places=2, max_digits=5)),
                ('cluster', models.CharField(db_column='Cluster', max_length=50)),
                ('highexprsc', models.SmallIntegerField(db_column='HighExprSC')),
                ('highrp', models.SmallIntegerField(db_column='HighRP')),
                ('highexprlm22', models.SmallIntegerField(db_column='HighExprLM22')),
                ('highexprgse60424', models.SmallIntegerField(db_column='HighExprGSE60424')),
                ('highexprcomb', models.SmallIntegerField(db_column='HighExprComb')),
            ],
        ),
        migrations.CreateModel(
            name='tsnePath',
            fields=[
                ('cancer', models.CharField(db_column='Cancer Type', max_length=50)),
                ('dataset', models.CharField(db_column='Dataset ID', max_length=50, primary_key=True, serialize=False)),
                ('original', models.CharField(db_column='Original tsne', max_length=300)),
                ('annotate', models.CharField(db_column='Annotated tsne', max_length=300)),
            ],
        ),
    ]
