# Generated by Django 3.0.4 on 2020-04-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkData', '0003_datacollect_dataset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollect',
            name='dataset_type',
            field=models.CharField(choices=[('TME', 'TME'), ('ICB', 'ICB')], db_column='Dataset Type', default='TME', max_length=20),
        ),
        migrations.AddField(
            model_name='datacollect',
            name='species',
            field=models.CharField(choices=[('Human', 'Human'), ('Mouse', 'Mouse')], db_column='Species', default='Human', max_length=20),
        ),
        migrations.AddField(
            model_name='datacollect',
            name='treatment',
            field=models.CharField(db_column='Treatment', default='None', max_length=50),
        ),
    ]
