# Generated by Django 3.0.4 on 2020-04-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkData', '0004_auto_20200418_1852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpLISA',
        ),
        migrations.DeleteModel(
            name='tsnePath',
        ),
    ]
