# Generated by Django 3.0.4 on 2020-04-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkData', '0005_auto_20200419_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadGeneFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genefile', models.FileField(db_column='Gene File', upload_to='upload/')),
            ],
        ),
    ]
