# Generated by Django 3.0.4 on 2020-06-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkData', '0008_auto_20200603_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollect',
            name='primary',
            field=models.CharField(db_column='Primary', default='None', max_length=50),
        ),
    ]
