# Generated by Django 3.0.4 on 2020-06-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkData', '0009_datacollect_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollect',
            name='dataset_type',
            field=models.CharField(choices=[('TME', 'TME'), ('ICB', 'ICB'), ('Normal', 'Normal')], db_column='Dataset Type', default='TME', max_length=20),
        ),
    ]
