# Generated by Django 3.0.4 on 2020-07-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkData', '0011_auto_20200703_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollect',
            name='therapy',
        ),
        migrations.RemoveField(
            model_name='datacollect',
            name='therapy_detailed',
        ),
        migrations.AddField(
            model_name='datacollect',
            name='treatment',
            field=models.CharField(db_column='Treatment', default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='datacollect',
            name='treatment_detailed',
            field=models.CharField(db_column='Detailed Treatment', default='None', max_length=50),
        ),
    ]
